name: simple_server

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  http: ^0.13.4
  mysql1: ^0.19.2
  mysql_client: ^0.0.11
  shelf: any
  shelf_cors_headers: ^0.1.2
  shelf_router: ^1.1.2
dev_dependencies: 
  test: ^1.20.2
